services:
  app:
    build: .
    image: mybdlai.azurecr.io/mohw/example-smart-app:latest
    ports:
      - "8002:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./example-smart-app:/usr/share/nginx/html
    restart: always